version: '3.8'

services:
  andreani-service:
    build: .
    container_name: andreani-token-service
    ports:
      - "3000:3000"
    environment:
      # Variables de entorno para las credenciales de Andreani
      # Puedes crear un archivo .env para configurar estas variables
      - NODE_ENV=production
      - ANDREANI_EMAIL=${ANDREANI_EMAIL:-}
      - ANDREANI_PASSWORD=${ANDREANI_PASSWORD:-}
    volumes:
      # Montar el código fuente para desarrollo (opcional)
      # Descomenta la siguiente línea si quieres hot reload durante desarrollo
      # - ./andreani.js:/app/andreani.js:ro
      
      # Montar directorio para screenshots de errores
      - ./screenshots:/app/screenshots
    restart: unless-stopped
    networks:
      - andreani-network
    # Configuración de recursos (opcional)
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    # Configuración de salud del contenedor
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  andreani-network:
    driver: bridge

volumes:
  screenshots:
    driver: local 